import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('GitHub Action metadata', () => {
  it('defines a reusable composite action for running ContextForge audit', async () => {
    const action = await readFile('action.yml', 'utf8');

    expect(action).toContain("using: 'composite'");
    expect(action).toContain('min-context-score:');
    expect(action).toContain('min-cache-score:');
    expect(action).toContain('min-security-score:');
    expect(action).toContain('sarif:');
    expect(action).toContain('summary:');
    expect(action).toContain('plan:');
    expect(action).toContain('comment:');
    expect(action).toContain('suggestions:');
    expect(action).toContain('badge:');
    expect(action).toContain('proof-pack:');
    expect(action).toContain('scorecard:');
    expect(action).toContain('surface-map:');
    expect(action).toContain('surface-inventory:');
    expect(action).toContain('mcp-audit:');
    expect(action).toContain('mcp-sarif:');
    expect(action).toContain('claude-audit:');
    expect(action).toContain('claude-sarif:');
    expect(action).toContain('trace-audit:');
    expect(action).toContain('review-kit:');
    expect(action).toContain('artifact-map:');
    expect(action).toContain('review-base-ref:');
    expect(action).toContain('agent-action-plan:');
    expect(action).toContain('pr-comment:');
    expect(action).toContain('suggestions-json:');
    expect(action).toContain('badge-svg:');
    expect(action).toContain('proof-pack-md:');
    expect(action).toContain('scorecard-md:');
    expect(action).toContain('surface-map-md:');
    expect(action).toContain('surface-inventory-md:');
    expect(action).toContain('mcp-audit-md:');
    expect(action).toContain('mcp-sarif:');
    expect(action).toContain('claude-audit-md:');
    expect(action).toContain('claude-sarif:');
    expect(action).toContain('trace-audit-md:');
    expect(action).toContain('review-kit-md:');
    expect(action).toContain('artifact-map-md:');
    expect(action).toContain('GITHUB_ACTION_PATH');
    expect(action).toContain('GITHUB_WORKSPACE');
    expect(action).toContain('GITHUB_STEP_SUMMARY');
    expect(action).toContain('npm exec --yes --package pnpm@11.2.2');
    expect(action).toContain('--sarif');
    expect(action).toContain('--summary');
    expect(action).toContain('--plan');
    expect(action).toContain('--comment');
    expect(action).toContain('--suggestions');
    expect(action).toContain('--badge');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" proof-pack');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" scorecard');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" surface-map');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" surface-inventory');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" mcp-audit');
    expect(action).toContain('--sarif \"${{ inputs.mcp-sarif }}\"');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" claude-audit');
    expect(action).toContain('--sarif \"${{ inputs.claude-sarif }}\"');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" trace-audit');
    expect(action).toContain('--summary \"${{ inputs.trace-audit }}\"');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" review-kit');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" artifact-map');
    expect(action).toContain('--base \"${{ inputs.review-base-ref }}\"');
    expect(action).toContain('if: always()');
    expect(action).toContain('node \"$GITHUB_ACTION_PATH/dist/cli.js\" audit');
  });
});
