export function createComparisonGuide(): string {
  const lines = [
    '# ContextForge Comparison Guide',
    '',
    'ContextForge is the maintainer readiness layer for Codex and Claude Code repositories.',
    'It complements token dashboards, repository packers, prompt evaluators, and security scanners by turning repo context quality into deterministic checks, CI artifacts, and agent-readable next actions.',
    '',
    '## Quick Comparison',
    '',
    '| Tool category | Examples | Strong at | ContextForge adds |',
    '| --- | --- | --- | --- |',
    '| Repository packers | Repomix, Gitingest | Combining files for LLM input | Smaller task packs, context health checks, security gates, and CI proof artifacts |',
    '| Token dashboards | ccusage, Token Use, Token Tracker | Showing cost and usage after sessions | Repo-level fixes for noisy instructions, cache instability, and context-pack planning |',
    '| Prompt and eval tools | promptfoo, CI eval suites | Testing model behavior and prompt quality | Repository readiness gates before agents ingest docs, rules, or PR context |',
    '| Agent security scanners | Snyk agent-scan, skill scanners | Finding prompt injection or risky agent components | Local repo instruction audits, README injection coverage, SARIF, and public benchmark fixtures |',
    '| Project memory conventions | AGENTS.md, CLAUDE.md, llms.txt | Giving agents a predictable place to start | Auditing, scaffolding, and keeping those files concise, safe, and measurable |',
    '',
    '## When To Use ContextForge',
    '',
    '- Before opening a PR that will be reviewed or modified by Codex or Claude.',
    '- Before asking an agent to trust a new repository, fork, benchmark, or external contribution.',
    '- Before a public launch where visitors need proof that the tool is real and deterministic.',
    '- When token dashboards show spend but not which repo surfaces caused waste.',
    '- When `AGENTS.md`, `CLAUDE.md`, or README instructions have grown by copying prompt folklore.',
    '',
    '## Best Together',
    '',
    '- Use Repomix when you need a whole-repo package for an LLM.',
    '- Use ccusage when you need broad local usage and cost reporting.',
    '- Use promptfoo when you need model/prompt evals.',
    '- Use ContextForge when you need the repository itself to prove it is ready for coding agents.',
    '',
    '## Proof Path',
    '',
    '```bash',
    'contextforge doctor --summary contextforge-doctor.md',
    'contextforge artifact-map --output docs/artifacts.md',
    'contextforge review-kit --base main --output contextforge-review-kit.md',
    'contextforge audit --summary contextforge-summary.md --plan contextforge-agent-plan.md --comment contextforge-pr-comment.md --suggestions contextforge-suggestions.json --badge contextforge-badge.svg',
    'contextforge pack --task "review auth regression" --budget 20000 --sessions',
    '```',
    ''
  ];
  return `${lines.join('\n')}\n`;
}
